driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
#  - name: windows-2008r2
#    driver_config:
#      box: chef/windows-server-2008r2-standard
#  - name: windows-2012r2
#    driver_config:
#      box: chef/windows-server-2012r2-standard
 - name: windows-2012-r2
   driver_config:
     box_url: E:\\artifactory\\windows2012r2min-hyperv.box
     provider: hyperv
     memory: 2048
     cpus: 1
     network:
       - ["private_network",{bridge: "internal_switch"}]

suites:
  - name: default
    run_list:
      - recipe[iis::default]
  - name: app
    run_list:
      - recipe[test::app]
  - name: module
    run_list:
      - recipe[test::module]
  - name: pool
    run_list:
      - recipe[test::pool]
  - name: root
    run_list:
      - recipe[test::root]
  - name: section
    run_list:
      - recipe[test::section]
  - name: site
    run_list:
      - recipe[test::site]
  - name: vdir
    run_list:
      - recipe[test::vdir]